<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ldg</string>
		<string>ledger</string>
		<string>ldgr</string>
	</array>
	<key>name</key>
	<string>Ledger</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.caps-not-allowed</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!^)([A-Z])</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.separator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(;;;;[^A-Z]*(\n|$))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.scheduler.config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.scheduler.config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(;;\s*scheduler?)\s*(;[^A-Z]*(\n|$))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(;;[^A-Z]*(\n|$))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.deprecated.todo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;[^A-Z]*)(todo)(.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;[^A-Z]*)(\b\w+:) ((?:\w+\W)+)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;[^A-Z]*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.date</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.transacton-number</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.payee</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d{4}[/-]\d{2}[/-]\d{2}) (\([^)]*\) )?((?:[-\w.,'$&amp;()]|(?&lt;! ) (?! ))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$ ?-?[\d\.,_]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.pending</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s+!)\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.reconciled</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(\*)\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(commodity|tag)\b ([^;]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.top-level</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(account)\b (?:[a-z]+:) ?([a-z0-9 ]+(?::|$))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(account)\b ([a-z]+)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(payee)\b ([^;]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.sub-directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.note</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(note)\b (.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.sub-directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.green</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(alias|format|default|check|assert)\b(?: (.*))?$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.price</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.date</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(P).(\d{4}[/-]\d{2}[/-]\d{2})</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.assets-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.assets-hilite-the-asset</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>message.error.commodity-amount-negative</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.class.commodity</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.at</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\ba(?:ssets)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(- ?[\d\.,_]+)\s+([a-zA-z_]+)(?:\s+(@)\s+|\s+(?=;)|\s*$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.assets-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.assets-hilite-the-asset</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.commodity-amount-positive</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.class.commodity</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.at</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\ba(?:ssets)?:) ?([^:;]+?(?::|(?=  )))[^;]*?([\d\.,_]+)\s+([a-zA-z_]+)(?:\s*(@)\s*|\s+(?=;)|\s*$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.assets-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.assets-hilite-the-asset</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>message.error.assets-dollars-out</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\ba(?:ssets)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?-(?:[\d\.,()+*/$-]| (?! )|$)+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.assets-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.assets-hilite-the-asset</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.assets-dollars-in</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\ba(?:ssets)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?(?:[\d\.,()+*/$]| (?! )|(?&lt;= )-(?= ))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.assets-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.assets-hilite-the-asset</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\ba(?:ssets)?:) ?([^:;]+?(?::|(?=  )|$))[^;]*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>message.error.liabilities-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.liabilities-the-liability</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>message.error.liabilities-dollars-out</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\bl(?:iabilities)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?-(?:[\d\.,()+*/$-]| (?! )|$)+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>message.error.liabilities-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.liabilities-the-liability</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.liabilities-dollars-in</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\bl(?:iabilities)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?(?:[\d\.,()+*/$]| (?! )|(?&lt;= )-(?= ))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>message.error.liabilities-hilite-the-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.liabilities-the-liability</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\bl(?:iabilities)?:) ?([^:;]+?(?::|(?=  )|$))[^;]*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.expenses</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.expenses</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.expenses-dollars-refund</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+[!*]?\s+(e(?:xpenses)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?-(?:[\d\.,()+*/$-]| (?! ))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.expenses</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.expenses</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.expenses-dollars-spent</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+[!*]?\s+(e(?:xpenses)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?(?:[\d\.,()+*/$-]| (?! ))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.expenses</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.expenses</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+[!*]?\s+(e(?:xpenses)?:) ?([^:;]+?(?::|(?=  )|$))[^;]*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.income</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.income</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.income-dollars-in</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+[!*]?\s+(i(?:ncome)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?-(?:[\d\.,()+*/$-]| (?! ))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.income</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.income</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>message.error.income-dollars-out</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+[!*]?\s+(i(?:ncome)?:) ?([^:;]+?(?::|(?=  )))[^;]*?(\(?\$ ?(?:[\d\.,()+*/$-]| (?! ))+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.income</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.income</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+[!*]?\s+(i(?:ncome)?:) ?([^:;]+?(?::|(?=  )|$))[^;]*</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ledger</string>
	<key>uuid</key>
	<string>806052d8-c579-43e0-918e-02ba9033b149</string>
</dict>
</plist>
