<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ldg</string>
		<string>ledger</string>
	</array>
	<key>name</key>
	<string>Ledger</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.scheduler-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.scheduler-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*;;\s*scheduler?)(\s*;.*)$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^;;;;.*</string>
			<key>name</key>
			<string>keyword.ledger.banner</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*;;.*\n</string>
			<key>name</key>
			<string>string.unquoted.ledger.header-bold-comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^account\s+.*  .*$</string>
			<key>name</key>
			<string>invalid.ledger</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.account-name</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.top-level</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.account-name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>account definition with children</string>
			<key>match</key>
			<string>^(account\s+)([a-z]+: ?)([a-z0-9 ]+(?::|$))([^;]*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ledger.name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>top level account/tag definition</string>
			<key>match</key>
			<string>^((?:tag|account)\s+)([^ ;]+)$</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments not allowed in account/tag definitions</string>
			<key>match</key>
			<string>^(tag|account)\s+.*[ ;].*$</string>
			<key>name</key>
			<string>invalid.ledger</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>will also mark trailing spaces as invalid but that's o.k.</string>
			<key>match</key>
			<string>^commodity\s+[^ ;]+(;|\s+[^ ;]).*$</string>
			<key>name</key>
			<string>invalid.ledger</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>technically *could* have semicolons, but that way lies madness</string>
			<key>match</key>
			<string>^payee\s+.*(;|  ).*$</string>
			<key>name</key>
			<string>invalid.ledger</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^payee\S.*$</string>
			<key>name</key>
			<string>invalid.ledger</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.ledger.payee</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(payee\s+)([^;]+)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ledger.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(commodity\s+)([^ ;]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.sub-directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.ledger</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s+note\s+)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.sub-directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.subdir-value</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s+(?:alias|format|default|check|assert)\s+)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.price</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ledger.date</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.commodity</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(P\s+)(\d{4}[/-]\d{2}[/-]\d{2}\s+)([a-zA-Z_]+\s+)(\$\s*-?[\d\.,_]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ledger.date</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.transaction-number</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.ledger.payee</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d{4}[/-]\d{2}[/-]\d{2}\s+)[!*]?\s*(\([^)]*\))?\s*(.+?)?(?=  |\t|$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.expenses-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.expenses-parent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.account-name</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ledger.money-out.expenses</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.money-in.expenses</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.commodity</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.at</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[!*\s]+([(\[]?[Ee](?:xpenses)?: ?)([^:;]+?(?::|(?=  |\t|$)))([^;]*?(?=  |\t|$))(?:(\s*=?\s*[(]?\s*[$£€¥₹]?\s*\d(?:[ \d\.,()+*/$-]+)?)|(\s*=?\s*[(]?\s*[$£€¥₹]?\s*-[ \d\.,()+*/$-]+))?(?:([a-zA-Z_]+\s*)(@\s*)?(\s*=?\s*[(]?\s*[$£€¥₹]?\s*[ \d\.,()+*/$-]+)?)?(?:(=[^;]+)?)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.assets-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.assets-parent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.account-name</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.money-in</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>message.error.ledger.money-out</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.commodity</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.at</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[!*\s]+([(\[]?[Aa](?:ssets)?: ?)([^:;]+?(?::|(?=  |\t|$)))([^;]*?(?=  |\t|$))(?:(\s*=?\s*[(]?\s*[$£€¥₹]?\s*\d(?:[ \d\.,()+*/$-]+)?)|(\s*=?\s*[(]?\s*[$£€¥₹]?\s*-[ \d\.,()+*/$-]+))?(?:([a-zA-Z_]+\s*)(@\s*)?(\s*=?\s*[(]?\s*[$£€¥₹]?\s*[ \d\.,()+*/$-]+)?)?(?:(=[^;]+)?)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>message.error.ledger.liabilities-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.liabilities-parent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.account-name</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.money-in</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>message.error.ledger.money-out</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.commodity</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.at</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[!*\s]+([(\[]?[Ll](?:iabilities)?: ?)([^:;]+?(?::|(?=  |\t|$)))([^;]*?(?=  |\t|$))(?:(\s*=?\s*[(]?\s*[$£€¥₹]?\s*\d(?:[ \d\.,()+*/$-]+)?)|(\s*=?\s*[(]?\s*[$£€¥₹]?\s*-[ \d\.,()+*/$-]+))?(?:([a-zA-Z_]+\s*)(@\s*)?(\s*=?\s*[(]?\s*[$£€¥₹]?\s*[ \d\.,()+*/$-]+)?)?(?:(=[^;]+)?)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.income-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.income-parent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.account-name</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>message.error.ledger.money-out</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.money-in</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.commodity</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.at</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[!*\s]+([(\[]?[Ii](?:ncome)?: ?)([^:;]+?(?::|(?=  |\t|$)))([^;]*?(?=  |\t|$))(?:(\s*=?\s*[(]?\s*[$£€¥₹]?\s*\d(?:[ \d\.,()+*/$-]+)?)|(\s*=?\s*[(]?\s*[$£€¥₹]?\s*-[ \d\.,()+*/$-]+))?(?:([a-zA-Z_]+\s*)(@\s*)?(\s*=?\s*[(]?\s*[$£€¥₹]?\s*[ \d\.,()+*/$-]+)?)?(?:(=[^;]+)?)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.equity-label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.equity-parent</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.ledger.account-name</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>message.error.ledger.money-out</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ledger.money-in</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.commodity</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.at</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.amount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[!*\s]+([(\[]?[Ee]quity?: ?)([^:;]+?(?::|(?=  |\t|$)))([^;]*?(?=  |\t|$))(?:(\s*=?\s*[(]?\s*[$£€¥₹]?\s*\d(?:[ \d\.,()+*/$-]+)?)|(\s*=?\s*[(]?\s*[$£€¥₹]?\s*-[ \d\.,()+*/$-]+))?(?:([a-zA-Z_]+\s*)(@\s*)?(\s*=?\s*[(]?\s*[$£€¥₹]?\s*[ \d\.,()+*/$-]+)?)?(?:(=[^;]+)?)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.ledger</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.ledger.todo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.ledger</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s*;.*)(todo)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.ledger</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.tag-without-value</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.ledger</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s*;[^:]*?)((?::\w+:|(?&lt;=:)\w+:)+)(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.ledger</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.tag-key</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.ledger.tag-value-payee</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>make payee name in tag be same as in payee directive</string>
			<key>match</key>
			<string>(\s*;\s*)([Pp]ayee: )(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.ledger</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.ledger.tag-key</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ledger.tag-value</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s*;\s*)(\w+: )(.*)$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*;.*$</string>
			<key>name</key>
			<string>comment.ledger</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ledger</string>
	<key>uuid</key>
	<string>50e628ee-56b8-4ab2-985d-8a49feff4f2d</string>
</dict>
</plist>
